import type { Metadata } from "next";
// import { Inter } from 'next/font/google';
// import "./globals.css";
// Google Fonts support
// const primaryFont = Inter({
//   display: 'swap',
//   subsets: ['latin'],
//   variable: '--font-primary',
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function FinanceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
        <header>FINANCE MODULE</header>
                {children}
      </div>

  );
}