import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import '../globals.css';

const primaryFont = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-primary',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <header>WEBSITE HEADER</header>
        {children}
      </body>
    </html>
  );
}