import type { Metadata } from "next";
// import { Inter } from 'next/font/google';
import MainRoot from "./_components/layout/MainRoot";
import {

  UsersRound ,
 
} from 'lucide-react';
interface Navigation {
  href: string;
  icon: React.ReactNode;
  label: string;
}

const navigations: Navigation[] = [
  {
    href: '/admin',
    icon: <UsersRound  color="black" size={20} />,
    label: 'Users',
  },
];


// const primaryFont = Inter({
//   display: 'swap',
//   subsets: ['latin'],
//   variable: '--font-primary',
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {   
  return (
    <MainRoot navigation={navigations}>
         {children}
         </MainRoot>
    
  );
}