import type { Metadata } from "next";
import { Inter } from 'next/font/google';

const primaryFont = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-primary',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className={`${primaryFont.variable}`}>
      {children}
    </section>
  );
}